### ISSUE TITLE
Test against OpenCV

### ISSUE THREAD

**Issue by kshitij12345** [kornia/kornia#311] opened 2019-11-01 12:59 UTC
It would be better to test the implemented functionality against OpenCV as the standard. As far as I know, few deep learning frameworks do verify the basic operations against numpy for sanity check.

https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_numpy_ndarray.py

https://github.com/chainer/chainer/blob/master/tests/chainerx_tests/unit_tests/routines_tests/test_logic.py

**Comment by edgarriba** [comment] 2019-11-02 08:22
@kshitij12345 you are opening a thing here :D

we already had an internal discussion with @ducha-aiki about opencv very recently. If it's only for sanity check and just use to get the expected values for some of integration tests I would say it's okay.

However, we should take into account that not all the implementations are strictly following opencv since some of them are slightly modified to be differentiable and targeting training. E.g. color conversions assume 0/1 range while in in opencv works too for 0/255.

**Comment by edgarriba** [comment] 2019-12-17 21:17
closing this since in the last PR we are already including regression test against data generated with opencv. There a lot of test yet to be covered. In case some wants to volunteer in that, feel free to add more tests.

**Closed by edgarriba** 2019-12-17 21:17 UTC
Labels: question
