### ISSUE TITLE
[BUG] Using Multi GPU support

### ISSUE THREAD

**Issue by Msabih** [kornia/kornia#130] opened 2019-05-09 04:23 UTC
While using tgm, I have come across one or two places in the code where the creation of new tensor has to be done on the device in the context otherwise the multi gpu training gives an error.

Should I give a pull request or perhaps you could think of better ways to solve this.

for example in torchgeometry/core/conversions.py in line 97-100, I changed the code as follows
```
device_points = points.device
scale: torch.Tensor = torch.tensor(1.) / torch.clamp(z_vec, eps)
scale = scale.to(device_points)
```

**Comment by edgarriba** [comment] 2019-05-09 10:46
@Msabih could you give us more information about your error, a screenshot of what you get, the devices you use, etc. I don't see why multi gpu should be a problem, since `scale` is derived from `z_vec` and this directly from `points`.

**Comment by Msabih** [comment] 2019-05-09 14:05
I was getting the typical error that these two tensors must be on the same devices. I will rebuild the library and get back to you with the error message. I am using multiple nvidia TX 1080 GPUs.

I didnt read the whole code, just got to the point of error, printed the device names of the tensors and scale was one device: 0 whereas I was using 6 and 7.

**Comment by Msabih** [comment] 2019-05-10 23:40
> @Msabih could you give us more information about your error, a screenshot of what you get, the devices you use, etc. I don't see why multi gpu should be a problem, since `scale` is derived from `z_vec` and this directly from `points`.

@edgarriba 

> /torchgeometry/core/conversions.py", line 98, in convert_points_from_homogeneous 
> return scale * points[..., :-1]  
> RuntimeError: binary_op(): expected both inputs to be on same device, but input a is on cuda:0 and in put b is on cuda:6

**Comment by edgarriba** [comment] 2019-05-11 05:29
It's interesting. How do you copy your tensors to cuda outside of the functions? Could you provide a small script so that we can reproduce the issue? Which torch version do you use? I'm fine with your fix, but we have been using this function in cuda multi gpu an no errors like this one. Would like to see why it happens first. /cc @bhack

**Comment by Msabih** [comment] 2019-05-12 02:41
> It's interesting. How do you copy your tensors to cuda outside of the functions? Could you provide a small script so that we can reproduce the issue? Which torch version do you use? I'm fine with your fix, but we have been using this function in cuda multi gpu an no errors like this one. Would like to see why it happens first. /cc @bhack

So I am taking a list of devices and giving it to the DataParallel as argument. Later on images are taken to first GPU for training like images = images.to(self.devices[0])

**Comment by edgarriba** [comment] 2019-05-12 06:48
Ok I see. Last, just to fully understand, if you print points, zvec and scale devices what do you get?

**Comment by edgarriba** [comment] 2019-05-28 11:07
@Msabih can you provide a unit test script where this can be reproduced ?

**Comment by Msabih** [comment] 2019-05-28 11:32
> @Msabih can you provide a unit test script where this can be reproduced ?

Okay, I will do it in a day as I find time. Just to note, I think this problem will not occur if multiple GPUs were used using DistributedDataParallel but only using DataParallel. Because I have switched to using DDP even on single machine with multiple GPUs as it distributes the load equally and is consistent. I did'nt try the perspective transform in that setting but I am pretty sure that this error will not come over there.

However to reproduce this issue on DataParallel, I will make a small test script.

**Comment by edgarriba** [comment] 2019-05-28 11:36
awesome. So DDP seems the way to go in general right ?

**Comment by Msabih** [comment] 2019-05-28 11:57
> awesome. So DDP seems the way to go in general right ?

Yes in general that is the case. But users may use DataParallel just because its easier or there could be a genuine use case. One use case is that Distributed Data Parallel takes more memory( its multiplied by number of nodes) if your Data Loader loads all the dataset at once however Data Parallel uses same amount of memory as single process use case. Another usecase might be if the cluster has free GPUs but is limited in terms of CPU Cores.

You might want to read this use case.
https://github.com/NVIDIA/apex/issues/269

For this library, pushing scale to the same device would work for all cases, Single, DataParallel and Distributed Data Parallel.

**Comment by edgarriba** [comment] 2019-06-13 15:04
@Msabih could you contribute with this patch and a quick test ?

**Comment by edgarriba** [comment] 2019-09-29 19:01
@Msabih @bhack was this solved ? Otherwise I'm closing it.

**Comment by edgarriba** [comment] 2020-01-31 11:57
I think this was already solved. Please, reopen in case anyone experience same issue

**Closed by edgarriba** 2020-01-31 11:57 UTC
Labels: bug, good first issue
