### ISSUE TITLE
[Feat] Differences between torchvision and kornia color jitter

### ISSUE THREAD

**Issue by rdevon** [kornia/kornia#565] opened 2020-05-11 16:13 UTC
The APIs for torchvision and kornia color jitter appear to be nearly identical, but the behavior is different.

How I tested this: I created kornia color jitter object and replicated the torchvision internals, allowing for one to pass in parameters and order to the PIL operations. Then I created a set of jitter parameters using kornia, then passed in these parameters (including the order) to the PIL transforms.

The transforms are similar, but not the same. Notably the kornia images tend to be brighter or darker than the corresponding torchvision ones, but the hue / etc appears to be the same (can't confirm contrast).

I suspected this was because of how kornia does brightness jitter, and I found that it does do things differently than PIL. PIL does a blend operation, which in the case of brightness amounts to multiplication by the brightness factor:
https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageEnhance.py#L36
(because the "other" image used in the blend is all zeros)

kornia does an addition operation:
https://github.com/kornia/kornia/blob/master/kornia/color/adjust.py#L220

Is this analysis correct and is this intentional? It would be good, since the APIs are so close, to have kornia do precisely what PIL / torchvision does, so that using kornia doesn't affect whether a model works or not. I've found that the same color jitter hyper parameters with kornia tend to saturate / drop pixels, which can lead to unstable learning in my case. I've checked brightness, but I don't know if other color jitter ops are also different.

**Comment by shijianjian** [comment] 2020-05-11 16:26
Hi @rdevon,

Since Kornia transformations aligned to OpenCV than PIL, we hereby chose to use OpenCV-like transformations. For details, you may check the doc:
https://kornia.readthedocs.io/en/latest/augmentation.html

We have also created a Colab that stratified the Torchvision and Kornia differences:
https://colab.research.google.com/drive/1T20UNAG4SdlE2n2wstuhiewve5Q81VpS

We also were considering having different backends back to some time. But did not have a concrete idea of the best practice. Please feel free to drop a PR if you would like to contribute!

**Comment by rdevon** [comment] 2020-05-11 17:06
What other ops behave differently besides brightness? I'm fine with having whatever working backend, and I intend to fork to make sure things closer to torchvision. I do have a few critiques on picking openCV over PIL:

The vast number of pytorch CV people use torchvision, so their code is already acclimated to PIL-like ops. It might be better to align with the majority first to make adoption less problematic.

The current brightness op does something fundamentally problematic at the pixel level. There is always a risk of oversaturating pixels with multiplication after clipping, I believe that addition / subtracting is even worse (and you can drop pixels with subtraction). This might explain why my models behave fundamentally different when I use kornia jitter with the same parameters as torchvision (i.e., doesn't work at all).

**Comment by shijianjian** [comment] 2020-05-12 13:29
Only AdjustContrast and AdjustBrightness. It is already documented but I will update the docs to emphasize the differences later.

For aligning with PIL, @edgarriba what do you think about having another suite of code for reproducing the PIL contrast & brightness adjustment?

**Comment by edgarriba** [comment] 2020-05-12 14:46
The reason to have this implementation is not only to follow OpenCV conventions. During the early days of implementing such image processing algorithms we were following Richard Szeliski's book `Computer Vision: Algorithms and Applications` where definition says **brightness is additive and contrast multiplicative** (see attached figure).

When we decided to match the augmentations interface with torchvision we realized that the implementation using PIL is not going according to the above definition.

Torchvision is getting rid of PIL too, so IDK about their plans for keeping such behaviour.

![image](https://user-images.githubusercontent.com/5157099/81698992-0d114780-9467-11ea-8dce-35f2081c8543.png)

**Comment by rdevon** [comment] 2020-05-12 16:20
So there might be great benefits to using OpenCV, but for models to work as intended it's important to maintain conventions, or at least design the API in a way that makes it easy to use kornia's color jitter without breaking how a model works. 

For PIL-style color jitter, at least in the range of brightness factors from 0-1 (half the possible sampling space from the torchvision API), there is almost no risk of losing information due to clamping (this only happens when you get a full black image with brightness factor 0). For additive brightness, since you're sampling negative values, the probability of dropping (from clamping) low-intensity pixels is quite high. This constitutes a loss of information in the input space which can fundamentally change how a model operates on it. I found that in my models, working was highly dependent on what brightness factor I used.

I have implemented PIL-style contrast and brightness here:
https://github.com/rdevon/kornia/commit/09d95360837e557a5d83f3bd891f0271d546ee62
which I think is correct.

Visually it's nearly identical, but there are subtle differences (which could be explained by how PIL quantizes data). But either way it might be worth adding these functions as well as a switch in the API.

**Comment by bluesky314** [comment] 2020-06-09 10:28
Even when I use ColorJitter with all 0's it changes the color of my images and totally fades them ! This is really unexpected behavior. 
I used : K.augmentation.ColorJitter(0., 0., 0., 0.)

Can anyone fix this?

**Comment by shijianjian** [comment] 2020-06-11 15:12
@bluesky314 Which version are you in? I do not have this issue on 0.3.2

**Comment by bluesky314** [comment] 2020-10-08 14:42
This is an interesting discussion, if more things could be pointed out

**Comment by justanhduc** [comment] 2020-10-14 09:29
One more thing I would like to point out is that the in the pip version, `ColorJitter` produces a tensor rank 4 for input shape rank 3. Not sure if this is fixed in master yet.

**Comment by shijianjian** [comment] 2020-10-15 02:33
@justanhduc Not fixed yet. It was an intended behaviour in previous versions, that all input will be transformed into BCHW format for 2D augmentations. It can be fixed but not sure if it is in need or not.

Can you open a new issue for this?

**Comment by justanhduc** [comment] 2020-10-19 02:38
@shijianjian sure. If it'snot too urgent I may work on a PR for the problem.

**Comment by edgarriba** [comment] 2020-10-19 13:39
@shijianjian what actions are we taking on this ?

**Comment by shijianjian** [comment] 2020-10-19 14:51
As afore discussed, we will not update the lib for PIL behaviours. But if #691 is true, then I think we shall consider adding another suite of PIL backend.

**Comment by shijianjian** [comment] 2022-08-02 13:43
Closed via #1611. `ColorJitter` is preserved as what happens in TorchVision, while we introduced `ColorJiggle` to keep the Kornia implementation.

**Closed by shijianjian** 2022-08-02 13:43 UTC
Labels: help wanted, feature request, Difficulty: easy
