### ISSUE TITLE
[Feat] kornia.Resize has a bad default for align_corners

### ISSUE THREAD

**Issue by pmeier** [kornia/kornia#777] opened 2020-11-10 14:21 UTC
## 🐛 Bug

`kornia.Resize` has a bad default for `align_corners` if `interpolation=="nearest"` or  `interpolation=="area"`.

## To Reproduce

```python
import torch
import kornia

transform = kornia.Resize(32, interpolation="nearest")

input = torch.rand(1, 3, 16, 16)
transform(input)
```

```
ValueError: align_corners option can only be set with the interpolating modes: linear | bilinear | bicubic | trilinear
```

## Expected behavior

This should work out of the box. You need to explicitly set `align_corners=None` to get this working. This is neither documented nor even accepted by the type annotations.

## Environment

`kornia==0.4.1`

**Comment by pmeier** [comment] 2020-11-10 14:31
I only know that you guys had problems with `align_corners` before so here is my proposal to fix this.

```python
def parse_align_corners(
    align_corners: Optional[bool], interpolation: str
) -> Optional[bool]:
    if align_corners is not None:
        return align_corners

    return (
        False
        if interpolation in ("linear", "bilinear", "bicubic", "trilinear")
        else None
    )
```

If you use that in the constructor of every transformation that has the `align_corners` parameter together with `align_corners=None` as default, you should be good. I imagine most users don't care about `align_corners` at all as long as it works.

**Comment by shijianjian** [comment] 2020-11-14 04:07
Yes, you are right. We should make a better default.

Should we set it to ```None``` directly for resize?

**Comment by pmeier** [comment] 2020-11-16 06:01
@shijianjian 

> Should we set it to `None` directly

I wouldn't recommend that:

```python
import torch
import kornia

transform = kornia.Resize(32, interpolation="bilinear", align_corners=None)

input = torch.rand(1, 3, 16, 16)
transform(input)
```

```
UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. 
Please specify align_corners=True if the old behavior is desired. 
See the documentation of nn.Upsample for details.
```

To avoid the error **and** the warning, you need to set `align_corners=False` if `interpolation in ("linear", "bilinear", "bicubic", "trilinear")` and `align_corners=None` otherwise. That is exactly what the `parse_align_corners` function does that I suggested in https://github.com/kornia/kornia/issues/777#issuecomment-724738810.

> for resize?

Again, I wouldn't recommend that. What is special about `resize`? Shouldn't this behavior consistent throughout the codebase? I would recommend doing something along the lines of 

```python
def resize(..., interpolation="bilinear", align_corners=None):
    align_corners = parse_align_corners(align_corners, interpolation)
    ...
```

In every function or module that takes the `align_corners` keyword.

**Comment by shijianjian** [comment] 2020-11-17 10:26
I see. That is reasonable. 

> To avoid the error and the warning, you need to set align_corners=False if interpolation in ("linear", "bilinear", "bicubic", "trilinear") and align_corners=None otherwise. That is exactly what the parse_align_corners function does that I suggested in #777 (comment).

From what you proposed, this is a general setting that fits all functions with (align_corners, interpolation), right?

**Comment by edgarriba** [comment] 2020-11-21 12:13
@pmeier do you think you can send a PR with it ? we are planning the release for v0.5 in a couple of weeks and this definitely can be good sanity patch. I guess this will also help with this #747

**Comment by pmeier** [comment] 2020-12-01 08:28
Sorry for the delay. I can give it a shot.

**Comment by edgarriba** [comment] 2021-04-05 14:07
@pmeier can you check https://github.com/kornia/kornia/issues/941 ? to see the next steps for augmentations and see hwo we could proceed with this ? /cc @shijianjian

**Comment by adamjstewart** [comment] 2022-11-27 16:44
This appears to be fixed in the latest release. The following has no errors:
```python
transform = kornia.geometry.transform.Resize(32, interpolation="nearest")
```
although the original error can be reproduced with:
```python
transform = kornia.geometry.transform.Resize(32, interpolation="nearest", align_corners=True)
```
I'm not actually sure how this works since `align_corners` still defaults to True...

**Comment by edgarriba** [comment] 2022-11-28 10:27
@pmeier shall we close this issue?

**Closed** 2024-04-02 22:31 UTC
Labels: help wanted, feature request, Difficulty: easy
