### ISSUE TITLE
Morphological erosion (and probably the other operations) does not work as expected

### ISSUE THREAD

**Issue by Manza12** [kornia/kornia#1030] opened 2021-05-24 10:30 UTC
## 🐛 Bug

The morphological erosion operation from the package kornia.morphology does not work as expected.

I compare the result of erosion with the scipy one and I get that they are not the same.

Here is a simple script that shows that

```import torch
from scipy.ndimage.morphology import grey_erosion
from kornia.morphology import erosion

input = torch.tensor([[0.5, 1., 0.3], [0.7, 0.3, 0.8], [0.4, 0.9, 0.2]])[None, None, :, :]
kernel = torch.tensor([[0., 1., 0.], [1., 1., 1.], [0., 1., 0.]])
output_kornia = erosion(input, kernel)[0, 0, :, :]
output_scipy = grey_erosion(input.numpy()[0, 0, :, :], structure=kernel.numpy())
print(output_kornia - output_scipy)
>>> tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**Comment by edgarriba** [comment] 2021-05-24 10:40
@Manza12 what's your proposed solution ?

**Comment by Manza12** [comment] 2021-05-24 12:36
I would use the [unfold](https://pytorch.org/docs/master/generated/torch.Tensor.unfold.html) method from PyTorch Tensor to manage the neighbourhood and perform the operation using the formula you can find [here](https://en.wikipedia.org/wiki/Mathematical_morphology#Grayscale_morphology).

The function will look like this:

```
...
# pad
se_h, se_w = kernel.shape
pad_e: List[int] = [se_w // 2, se_w // 2, se_h // 2, se_h // 2]
output: torch.Tensor = F.pad(tensor, pad_e, mode='constant', value=1.)

# computation
output = output.unfold(2, se_h, 1).unfold(3, se_w, 1)
output = torch.amin(output - kernel, (4, 5))

return output 
```
Do you want me to make a PR? I may also check other operations...

**Comment by shijianjian** [comment] 2021-05-24 14:58
Yes, please go for it if it is our current best solution.

**Comment by shaunster0** [comment] 2021-06-18 09:16
I think I know what the issue is here. If u change line
https://github.com/kornia/kornia/blob/master/kornia/morphology/morphology.py#L142

to set the border to zero (ie. border_value = 0), output agrees with scipy erosion. The difference with scipy only existed at the edges (interestingly dilation didnt have this issue, output agrees with scipy).

**Comment by edgarriba** [comment] 2021-06-25 10:56
@Manza12 @shaunster0 could any of you send a quick PR with this ?

**Comment by shaunster0** [comment] 2021-07-04 06:09
so I tried making a PR here, but with border_value = 0 it broke 12 tests in morphology package ... seems the tests have been created to use border_value = max_val  
Upon further consideration, I guess this is a subjective issue ... scipy erosion uses default border_value = 0 but kornia erosion currently uses border_value = max_val which isnt necessarily wrong. So I'm not clear enough here to proceed ... do we want default values that are consistent with scipy, or are we ok with default values that differ from scipy erosion but arent exactly wrong? If we want consistency with scipy a dozen tests in morphology package need to be amended.

**Comment by Manza12** [comment] 2021-07-04 08:05
If I am not wrong, scipy does not use 'constant' as default border handler, it uses 'reflect'. This is taken from usual convolution standards. However, in the case of mathematical morphology, the usual border handler is 'geodesic', which ensures that the outside values are not taken into account for the computation of the minimum/maximum. This is kind of the analog to 'constant' = 0 in usual convolution.
I have not seen this approach in any morphology package, but I implemented here since I think is a good default approach.


________________________________

**Comment by edgarriba** [comment] 2021-10-10 11:17
@Manza12 @ducha-aiki is this an issue anymore ? otherwise lets close this ticket

**Comment by ducha-aiki** [comment] 2021-10-10 11:30
I think we can close

**Closed** 2021-10-10 11:41 UTC
Labels: bug :bug:, P1 🚨, module: morphology
