### ISSUE TITLE
parameter alpha in focal loss is not the same as that of paper

### ISSUE THREAD

**Issue by Xinchengzelin** [kornia/kornia#2371] opened 2023-05-09 12:30 UTC
### Describe the bug

The parameter alpha in focal loss is a scalor, so it couldn't has the effect of balanced the different classes. I think alpha should be a  tensor with n_classses element and every value refers to the weiht of this class

### Reproduction steps

```bash
Please refer to the description
```

### Expected behavior

Please refer to the description

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```


### Additional context

_No response_

**Comment by johnnv1** [comment] 2023-05-09 20:48
Hi, tks for the report, I'm closing it since it's a duplicate of #875 (and #2365). but please, feel free, to interact on the older issue, or open a PR to fix it.

**Closed by johnnv1** 2023-05-09 20:48 UTC
Labels: help wanted
